# My workflow

name: My first workflow

# Trigger: Webhook event
on: [push, pull_request]

jobs:
  # job
  job_1:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      # 1번째 step
      - name: My first step
        uses: actions/checkout@v2

      # [python] 설치
      - name: python in one code
        uses: actions/setup-python@v5.1.0
        
      # [python] 실행
      - name: run python 
        run: python myapp.py
        shell: bash
        
      # 2번째 step에서 "Hello World"를 함
      - name: My second step
        run: echo "Hello World"
        shell: bash
        
      # 3번째 step
      - name: My third step
        run: |
          echo "first hello"
          echo "second hello!"
        shell : bash

      - name: The job has succeeded
        if: ${{ success() }}
        run: echo "successfully completed"
        
